# Generated by Django 5.0 on 2023-12-28 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huddleapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huddleuser',
            name='accountability',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='huddleuser',
            name='notifications',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='huddleuser',
            name='personal_data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='huddleuser',
            name='public_links',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='huddleuser',
            name='settings',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='huddleuser',
            name='skill_levels',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='reactions',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='links',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='open_positions',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='resources',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tasks',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='users_to_skills',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='skills',
            field=models.ManyToManyField(related_name='project_groups', to='huddleapi.skill'),
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='social_networks_links',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='users_to_skills',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='resources',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='resources',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_groups', to='huddleapi.skill'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='social_networks_links',
            field=models.JSONField(null=True),
        ),
    ]
