# Generated by Django 5.0 on 2023-12-28 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huddleapi', '0002_alter_huddleuser_accountability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huddleuser',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='users_with_skill', to='huddleapi.skill'),
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='project_groups', to='huddleapi.skill'),
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='users_requests',
            field=models.ManyToManyField(blank=True, related_name='project_group_requested', to='huddleapi.huddleuser'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='skill',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='study_groups', to='huddleapi.skill'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='users_requests',
            field=models.ManyToManyField(blank=True, related_name='study_group_requested', to='huddleapi.huddleuser'),
        ),
    ]
