# Generated by Django 5.0 on 2023-12-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huddleapi', '0003_alter_huddleuser_skills_alter_projectgroup_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='group_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='reserved',
            field=models.TextField(null=True),
        ),
    ]
