# Generated by Django 5.0 on 2023-12-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huddleapi', '0006_remove_chat_group_id_alter_studygroup_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectgroup',
            name='archived_projects',
            field=models.ManyToManyField(blank=True, related_name='group_archived', to='huddleapi.project'),
        ),
    ]
