# Generated by Django 5.0 on 2023-12-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huddleapi', '0007_alter_projectgroup_archived_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup',
            name='skill',
        ),
        migrations.AddField(
            model_name='studygroup',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='study_groups', to='huddleapi.skill'),
        ),
    ]
