# Generated by Django 5.0 on 2023-12-29 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huddleapi', '0008_remove_studygroup_skill_studygroup_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup',
            name='skills',
        ),
        migrations.AddField(
            model_name='studygroup',
            name='skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_groups', to='huddleapi.skill'),
        ),
    ]
