# Generated by Django 5.0 on 2023-12-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huddleapi', '0010_remove_studygroup_skill_studygroup_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectgroup',
            name='coordinators',
            field=models.ManyToManyField(blank=True, related_name='project_groups_coordinated', to='huddleapi.huddleuser'),
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='project_groups', to='huddleapi.huddleuser'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='coordinators',
            field=models.ManyToManyField(blank=True, related_name='study_groups_coordinated', to='huddleapi.huddleuser'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='study_groups', to='huddleapi.huddleuser'),
        ),
    ]
